### ISSUE TITLE
ValueError: Bad Conformer Id

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/sygma#1]
When I use the package from KNIME I get the following error.

```
 conf = self.mol.GetConformer(0)
ValueError: Bad Conformer Id
```

To get rid of the error I added the `RDKit Add Conformers` node before it with nr of conformers set to 1.
Can this error be catched and handled, so conformers are no longer required?

**Comment by ridderl** [comment]
The way I did this was to tick the `Generate 2D Coordinates` button in the `RDKit from Molecule` node. Then you don't need the `RDKit Add Conformers` node.

I will remove the requirement of conformers anyway ....
