### ISSUE TITLE
Add to PyPi

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/sygma#2]

**Comment by ridderl** [comment]
@sverhoeven I forgot what you said about the dependency on rdkit. The requirement of rdkit is checked but not resolved in the current setup.py of the sygma package. Isn't that a problem? When installing the PyPi package in the context of knime, rdkit is hopefully already there, but outside knime we can't rely on that.

A solution could be to package both in PyPi and Conda and suggest using Conda (in the error message provided in setup.py) when rdkit is found to be lacking. Do you agree?

**Comment by sverhoeven** [comment]
The setup.py expects that rdkit is already installed and if not raises an Exception.
rdkit is not mentioned as a requirement in setup.py or requirements.txt because it can not be installed with pip.

Yep, I agree pointing to http://www.rdkit.org/docs/Install.html (which explains rdkit install with conda) in the setup.py raised exception seems to be the best solution.
The rdkit dep is also described in the README, which will appear on PyPi.

We could also have a look at how other Python packages with rdkit as requirement are implemented, see https://pypi.python.org/pypi?%3Aaction=search&term=rdkit&submit=search

**Comment by ridderl** [comment]
Thanks. It looks like other python packages also do not automatically install rdkit.
For example: https://pypi.python.org/pypi/oddt/0.2.0
