### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/sygma#4]
On the KNIME node I would like to link to the installation instructions. 
The current instructions are too minimalistic.

Would like instructions using Conda for Linux and Windows.
Related to #2 and #3

**Comment by ridderl** [comment]
SyGMa is added pypi and this option for installation of sygma is added to the readme.
Can you indicate what else you need for KNIME?
Conda is not relevant for KNIME, is it?

**Comment by sverhoeven** [comment]
Now the sygma install requires only 2 steps (rdkit + pip install sygma).
When sygma is also in Conda (#3) then a single step (conda install sygma) would suffice.

Having 2 steps is fine for now.
